---
defaults: &defaults
  working_directory: ~/dropwizard-sqs

save_cache: &save_cache
  save_cache:
    paths:
      - ~/.gradle/wrapper
      - ~/.gradle/caches
      - ~/.local
      - ~/.cache/pip
    key: dw-sqs-deps-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}

restore_cache: &restore_cache
  restore_cache:
    keys:
      - dw-sqs-deps-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
      - dw-sqs-deps-{{ checksum "build.gradle" }}
      - dw-sqs-deps-

persist_to_workspace: &persist_to_workspace
  persist_to_workspace:
    root: ~/dropwizard-sqs
    paths:
      - .

attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/dropwizard-sqs

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      JVM_OPTS: -Djava.awt.headless=true -server -Xmx1G
      TERM: dumb

    steps:
      - checkout
      - <<: *restore_cache
      - run: ./gradlew classes testClasses
      - <<: *save_cache
      - <<: *persist_to_workspace

  test:
    <<: *defaults
    docker:
      - image: circleci/openjdk:8-jdk
      - image: pafortin/goaws
        entrypoint: /bin/sh
        command: -c 'echo "$GOAWS_CONF" > /conf/goaws.yaml && cat /conf/goaws.yaml && exec /goaws_linux_amd64 -debug'
        environment:
          GOAWS_CONF: |
            Local:
              Host: 0.0.0.0
              Port: 4100
              LogMessages: true
              LogFile: ./goaws_messages.log
              Queues:
                - Name: functional_test_queue
              Topics:
                - Name: functional_test_queue
                  Subscriptions:
                    - QueueName: functional_test_queue
                      Raw: false
    steps:
      - <<: *attach_workspace
      - <<: *restore_cache
      - run: ./gradlew check
      - run: ./gradlew jacocoTestReport
      - store_test_results:
          path: ./build/test-results/test
      - <<: *save_cache
      - <<: *persist_to_workspace

  codecov:
    <<: *defaults
    docker:
      - image: circleci/python:latest
    steps:
      - <<: *attach_workspace
      - <<: *restore_cache
      - run: pip install --user --upgrade codecov
      - run: ~/.local/bin/codecov --token=${CODECOV_TOKEN}
      - <<: *save_cache

  snapshot:
    <<: *defaults
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - <<: *attach_workspace
      - <<: *restore_cache
      - run: ./gradlew publish -PsmartThingsUserName=$ARTIFACTORY_USERNAME -PsmartThingsPassword=$ARTIFACTORY_PASSWORD

  release:
    <<: *defaults
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - <<: *attach_workspace
      - <<: *restore_cache
      - run: ./gradlew bintrayUpload


workflows:
  version: 2
  build-ci:
    jobs:
      - build
      - test:
          requires:
            - build
      - codecov:
          requires:
            - test
      - snapshot:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - master-1.2.x
      - release:
          requires:
            - test
          filters:
            branches:
              only:
                - release
                - release-1.2.x
