version: '2'
services:
  yopa:
    container_name: docker_sqs_goaws
    image: pafortin/goaws:latest
    ports:
      - 4100:4100
    volumes:
     - ./etc/local:/conf
    entrypoint: "/goaws_linux_amd64 -debug"
