---
defaults: &defaults
  working_directory: ~/dropwizard-sqs

save_cache: &save_cache
  save_cache:
    paths:
      - ~/.gradle/wrapper
      - ~/.gradle/caches
      - ~/.local
      - ~/.cache/pip
    key: dw-sqs-deps-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}

restore_cache: &restore_cache
  restore_cache:
    keys:
      - dw-sqs-deps-{{ checksum "build.gradle" }}-{{ checksum "gradle.properties" }}
      - dw-sqs-deps-{{ checksum "build.gradle" }}
      - dw-sqs-deps-

persist_to_workspace: &persist_to_workspace
  persist_to_workspace:
    root: ~/dropwizard-sqs
    paths:
      - .

attach_workspace: &attach_workspace
  attach_workspace:
    at: ~/dropwizard-sqs

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      JVM_OPTS: -Djava.awt.headless=true -server -Xmx1G
      TERM: dumb

    steps:
      - checkout
      - <<: *restore_cache
      - run: ./gradlew classes testClasses -PsmartThingsUserName=$ARTIFACTORY_USERNAME -PsmartThingsPassword=$ARTIFACTORY_PASSWORD
      - <<: *save_cache
      - <<: *persist_to_workspace

  test:
    <<: *defaults
    docker:
      - image: circleci/openjdk:8-jdk
        environment:
          AWS_ENDPOINT_URL: "http://goaws:4100"
          TOPIC_ARN: "arn:aws:sns:us-east-1:000000000000:functional_test_queue"
          GRADLE_USER_HOME: ~/repo/.gradle
      - image: pafortin/goaws:1.0.1
        environment:
          PUBLICHOST: goaws
        name: goaws
    steps:
      - <<: *attach_workspace
      - <<: *restore_cache
      - run: |
         sudo apt-get update
         sudo apt-get -y install libatomic1 python-pip
         pip install boto3
         mkdir ~/.aws
         cp ./etc/circleci/credentials ~/.aws
      - run: python ./etc/circleci/goaws.py --endpoint-url="http://goaws:4100"
      - run: ./gradlew check jacocoTestReport -PsmartThingsUserName=$ARTIFACTORY_USERNAME -PsmartThingsPassword=$ARTIFACTORY_PASSWORD -PawsEndpointUrl=$AWS_ENDPOINT_URL -PtopicArn=$TOPIC_ARN --stacktrace --debug
      - store_test_results:  
          path: ./build/test-results/test
      - <<: *save_cache
      - <<: *persist_to_workspace

  snapshot:
    <<: *defaults
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - <<: *attach_workspace
      - <<: *restore_cache
      - run: ./gradlew publish -PsmartThingsUserName=$ARTIFACTORY_USERNAME -PsmartThingsPassword=$ARTIFACTORY_PASSWORD

  release:
    <<: *defaults
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - <<: *attach_workspace
      - <<: *restore_cache
      - run: ./gradlew publish -PsmartThingsUserName=$ARTIFACTORY_USERNAME -PsmartThingsPassword=$ARTIFACTORY_PASSWORD


workflows:
  version: 2
  build-ci:
    jobs:
      - build:
          context: smartthingsoss
      - test:
          context: smartthingsoss
          requires:
            - build
      - snapshot:
          context: smartthingsoss
          requires:
            - test
          filters:
            branches:
              only: master
      - release:
          context: smartthingsoss
          requires:
            - test
          filters:
            branches:
              only: release
